swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Gamification Server'
  description: "A simple Gamification server for application developpers. It allows
  them to manage their gamification API"
host: "localhost:8080"
basePath: "/api"
schemes:
  - http

paths:
  /badge:
    post:
      tags:
      - "badges"
      summary: "Create a badge for your app"
      description: "Post a badge with an ID"
      operationId: 'createBadge'
      consumes:
      - application/json
      parameters:
        - $ref: '#/parameters/badge'
      responses:
        '201':
          description: created
          schema:
            type: object

    get:
      tags:
      - "badges"
      description: get the list of the application badges
      operationId: getBadges
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/appKey'
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Badge'

  /badge/{badgeName}:
    post:
      tags:
      - "badges"
      description: modify the "id" badge of the "id" app
      summary: "modify a badge"
      operationId: modifiyBadge
      consumes:
        -application/json
      parameters:
        - $ref: '#/parameters/badge'
        - $ref: '#/parameters/badgeName'
      responses:
        '201':
          description: modified
          schema:
            $ref: '#/definitions/Badge'


  /pointScale:
    post:
      description: create a pointScale
      operationId: createPointScale
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/pointScale'
      responses:
        '201':
          description: created
          schema:
            type: object

  /pointScales/{pointScaleName}/{user}:
    get:
      description: return the points the user have
      operationId: getPoints
      parameters:
        - $ref: '#/parameters/pointScaleName'
        - $ref: '#/parameters/appKey'
        - $ref: '#/parameters/username'
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: int

  /pointScales/{pointScaleName}/users:
    get:
      description: return the list of all the users in the pointScale and the points they have
      operationId: getAllUsersFromPointScale
      parameters:
        - $ref: '#/parameters/appKey'
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Badge'


  /rules:
    post:
      description: create a rule for an app
      operationId: createRule
      consumes:
        -application/json
      parameters:
        in: body
        name: rule
        schema:
          $ref: '#/definitions/Rules'
      responses:
        '201':
          description: modified
          schema:
            type: object

  /events:
    post:
      description: send an event
      operationId: sendEvent
      consumes:
        -application/json
      parameters:
        - $ref: '#/parameters/usernameBody'
        - $ref: '#/parameters/ruleName'
        - $ref: '#/parameters/appKey'
      responses:
        '201':
          description: modified
          schema:
            type: object
parameters:
  badge:
    name: badge
    in: body
    required: true
    schema:
      $ref: '#/definitions/Badge'

  appKey:
    name: appKey
    in: header
    required: true
    type: int

  badgeName:
    name: badgeName
    in: path
    required: true
    type: string

  username:
    name: username
    in: path
    required: true
    type: string

  usernameBody:
    name: username
    in: body
    required: true
    type: string

  pointScale:
    name: pointScale
    in: path
    required: true
    schema:
      $ref: '#/definitions/PointScale'

  pointScaleName:
    name: pointScaleName
    in: path
    required: true
    type: string

  ruleName:
    in: path
    name: ruleName
    required: true
    type: string

definitions:
  Badge:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      appKey:
        type: int
    required:
      - name
      - description
      - appKey

  PointScale:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      appKey:
        type: int
    required:
      - name
      - description
      - appKey

  Rules:
    type: object
    properties:
      appKey:
        type: integer
      name:
        type: string
      description:
        type: string
      points:
        type: int
      pointScale:
        $ref: '#/definitions/PointScale'
      badge:
        $ref: '#/definitions/Badge'
    required:
      - appKey
      - name
      - description
      - points
      - pointScale
      - badge

