swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Gamification Server'
  description: "A simple Gamification server for application developpers. It allows
  them to manage their gamification Application"
host: "localhost:8080"
basePath: "/api"
schemes:
  - "http"

paths:
  /badge:
    post:
      tags:
        - "badges"
      summary: "Create a badge for your app"
      description: "Post a badge with an ID"
      operationId: 'createBadge'
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/badge'
      responses:
        '201':
          description: created
          schema:
            type: object
        '400':
          description: already exist
          schema:
            type: object

    delete:
      tags:
        - "badges"
      description: delete the requested bage
      operationId: deleteBadge
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/badge'
      responses:
        '200':
          description: deleted
          schema:
            type: object
        '400':
          description: could not be found
          schema:
            type: object

  /badge/{badgeName}:
    get:
      tags:
        - "badges"
      description: get the requested bage
      operationId: getBadge
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/appKey'
        - $ref: '#/parameters/badgeName'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Badge'
        '404':
          description: bagde not found
          schema:
            type: object

    put:
      tags:
        - "badges"
      description: modify the "id" badge of the "id" app
      operationId: modifiyBadge
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/badge'
        - $ref: '#/parameters/badgeName'
        - $ref: '#/parameters/appKey'
      responses:
        '201':
          description: modified
          schema:
            type: object

  /badges:
    get:
      tags:
        - "badges"
      description: get the list of the application badges
      operationId: getBadges
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/appKey'
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Badge'

  /pointScale:
    post:
      tags:
        - "pointScales"
      description: create a pointScale
      operationId: createPointScale
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/pointScale'
      responses:
        '201':
          description: created
          schema:
            type: object
        '400':
          description: already exist
          schema:
            type: object
    put:
      tags:
        - "pointScales"
      description: update a pointScale
      operationId: updatePointScale
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/pointScale'
      responses:
        '201':
          description: created
          schema:
            type: object
        '400':
          description: failed to update the pointScale
          schema:
            type: object
    delete:
      tags:
        - "pointScales"
      description: delete a pointScale
      operationId: deletePointScale
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/pointScale'
      responses:
        '201':
          description: deleted
          schema:
            type: object
        '400':
          description: failed to delete the pointScale
          schema:
            type: object

  /pointScales/{pointScaleName}:
    get:
      tags:
        - "pointScales"
      description: return the pointScale wanted
      operationId: getPointScale
      parameters:
        - $ref: '#/parameters/pointScaleName'
        - $ref: '#/parameters/appKey'
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/PointScale'
        '404':
          description: user not found
          schema:
            type: object

  /pointScales/{pointScaleName}/{username}:
    get:
      tags:
        - "pointScales"
      description: return the points the user have
      operationId: getPoints
      parameters:
        - $ref: '#/parameters/pointScaleName'
        - $ref: '#/parameters/appKey'
        - $ref: '#/parameters/username'
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: integer
        '404':
          description: user not found
          schema:
            type: object

  /pointScales/{pointScaleName}/users:
    get:
      tags:
        - "pointScales"
      description: return the list of all the users in the pointScale and the points they have
      operationId: getAllUsersFromPointScale
      parameters:
        - $ref: '#/parameters/appKey'
        - $ref: '#/parameters/pointScaleName'
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              type: object


  /rule:
    post:
      tags:
        - "rules"
      description: create a rule for an app
      operationId: createRule
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/rule'
      responses:
        '201':
          description: created
          schema:
            type: object
        '400':
          description: already exist
          schema:
            type: object
    put:
      tags:
        - "rules"
      description: update a rule for an app
      operationId: updateRule
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/rule'
      responses:
        '201':
          description: created
          schema:
            type: object
        '400':
          description: already exist
          schema:
            type: object
    delete:
      tags:
        - "rules"
      description: delete a rule for an app
      operationId: deleteRule
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/rule'
      responses:
        '201':
          description: delete
          schema:
            type: object
        '400':
          description: already exist
          schema:
            type: object

  /rule/{ruleName}:
    get:
      tags:
        - "rules"
      description: get the wanted application rule
      operationId: getRule
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/appKey'
        - $ref: '#/parameters/ruleName'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Rule'


  /rules:
    get:
      tags:
        - "rules"
      description: get the list of the application rules
      operationId: getRules
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/appKey'
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Rule'

  /events:
    post:
      tags:
        - "events"
      description: send an event
      operationId: sendEvent
      consumes:
        - application/json
      parameters:
        - name: event
          in: body
          required: true
          schema:
            $ref: '#/definitions/Event'
      responses:
        '201':
          description: modified
          schema:
            type: object
parameters:
  badge:
    name: badge
    in: body
    required: true
    schema:
      $ref: '#/definitions/Badge'

  appKey:
    name: appKey
    in: header
    required: true
    type: integer

  badgeName:
    name: badgeName
    in: path
    required: true
    type: string

  username:
    name: username
    in: path
    required: true
    type: string

  pointScale:
    name: pointScale
    in: body
    required: true
    schema:
      $ref: '#/definitions/PointScale'

  pointScaleName:
    name: pointScaleName
    in: path
    required: true
    type: string

  rule:
    name: rule
    in: body
    required: true
    schema:
      $ref: '#/definitions/Rule'

  ruleName:
    name: ruleName
    in: path
    required: true
    type: string


definitions:
  Badge:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      appKey:
        type: integer
    required:
      - name
      - description
      - appKey

  PointScale:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      appKey:
        type: integer
    required:
      - name
      - description
      - appKey

  Rule:
    type: object
    properties:
      appKey:
        type: integer
      name:
        type: string
      description:
        type: string
      points:
        type: integer
      pointScaleName:
        type: string
      badgeName:
        type: string
    required:
      - appKey
      - name
      - description
      - points
      - pointScale
      - badge

  Event:
    type: object
    properties:
      appKey:
        type: integer
      ruleName:
        type: string
      username:
        type: string
    required:
      - appKey
      - rules
      - username
