swagger: '2.0'
info:
  version: '0.1.0'
  title: badges API
  description: The badges API
host: localhost:8080
basePath: /api
schemes:
  - http
  paths:
    /pointScale:
      post:
        description: create a pointScalte
        operationId: createPointScale
        consumes:
          -application/json
        parameters:
          name: pointScale
          in: body
          required: true
          schema:
            $ref: '#/definitions/PointScale'
          responses:
            '201':
              description: created
              schema:
                type: object


    /pointScale/update/userPoints:
      post:
        description: add/substract points to a user
        operationId: updateUser
        consumes:
          -application/json
        parameters:
          name: pointScale
          in: body
          required: true
          schema:

    /badge:
      post:
        description: create a badge
        operationId: createBadge
        consumes:
          -application/json
        parameters:
          name: badge
          in: body
          required: true
          schema:
            $ref: '#/definitions/Badges'
          responses:
            '201':
              description: created
              schema:
                type: object
      get:
        description: get the list of the application badges
        opetationId: getBadges
        produces:
        - application/json
        responses:
          '200':
            descritpion: success
            schema:
              type: array
              items:
                $ref: '#/definitions/Badge'

    /badge/modify:
      post:
        description: modify a badge
        operationId: modifiyBadge

    /badge/delete:
      post:
        description: delete a badge
        operationId: deleteBadge

  definitions:
    Badge:
      type: object
      properties:
        name:
          type: string
        description:
          type: string

    PointScale:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
