swagger: '2.0'
info:
  version: '0.1.0'
  title: badges API
  description: The badges API
host: 192.168.99.100
basePath: /api
schemes:
  - http

paths:
  /badges:
    post:
      description: create a badge
      operationId: createBadge
      consumes:
        -application/json
      parameters:
        name: badge
        in: body
        required: true
        schema:
          $ref: '#/definitions/Badges'
        responses:
          '201':
            description: created
            schema:
              type: object
    get:
      description: get the list of the application badges
      opetationId: getBadges
      produces:
      - application/json
      responses:
        '200':
          descritpion: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Badges'
definitions:
  Badges:
    type: object
    properties:
      name:
        type: string
      description:
        type: string